// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVWEuCnQOOKY0zU2n9gRFtp-U0MO5v_xI',
    appId: '1:775865654025:web:07d5b30b036235c291d1d8',
    messagingSenderId: '775865654025',
    projectId: 'budgetbuddy-67d83',
    authDomain: 'budgetbuddy-67d83.firebaseapp.com',
    storageBucket: 'budgetbuddy-67d83.appspot.com',
    measurementId: 'G-SX7EWTKWW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Fme4giDZLVuzMm8oEiIu4TrV3rXh4uQ',
    appId: '1:775865654025:android:87667303f161368e91d1d8',
    messagingSenderId: '775865654025',
    projectId: 'budgetbuddy-67d83',
    storageBucket: 'budgetbuddy-67d83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXAlwWo-GB2A_m_CPK01ueta6eEddg4bk',
    appId: '1:775865654025:ios:01698b41dd40740791d1d8',
    messagingSenderId: '775865654025',
    projectId: 'budgetbuddy-67d83',
    storageBucket: 'budgetbuddy-67d83.appspot.com',
    iosBundleId: 'com.example.budgetBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXAlwWo-GB2A_m_CPK01ueta6eEddg4bk',
    appId: '1:775865654025:ios:01698b41dd40740791d1d8',
    messagingSenderId: '775865654025',
    projectId: 'budgetbuddy-67d83',
    storageBucket: 'budgetbuddy-67d83.appspot.com',
    iosBundleId: 'com.example.budgetBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVWEuCnQOOKY0zU2n9gRFtp-U0MO5v_xI',
    appId: '1:775865654025:web:66a7c1c69c36ba0191d1d8',
    messagingSenderId: '775865654025',
    projectId: 'budgetbuddy-67d83',
    authDomain: 'budgetbuddy-67d83.firebaseapp.com',
    storageBucket: 'budgetbuddy-67d83.appspot.com',
    measurementId: 'G-4RH4ZHGEZZ',
  );
}
